version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      include: "scope"
    ignore:
      # typescript-eslint does not support TS 7.0
      - dependency-name: "typescript"
        versions: [">=7.0.0"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      include: "scope"
